backend:
  name: git-gateway
  branch: main
  site_domain: tarcisio-lima.netlify.app

media_folder: "imagens/uploads"
public_folder: "/imagens/uploads"

collections:
  - name: "agenda"
    label: "Agenda de Shows"
    folder: "_data"
    files:
      - file: "_data/agenda.yml"
        label: "Lista de Shows"
        name: "shows"
        fields:
          - label: "Shows"
            name: "items"
            widget: "list"
            fields:
              - {label: "Dia", name: "dia", widget: "string"}
              - {label: "Mês", name: "mes", widget: "string"}
              - {label: "Cidade", name: "cidade", widget: "string"}
              - {label: "Local do Evento", name: "local", widget: "string"}

  - name: "site"
    label: "Configurações do Site"
    files:
      - file: "_data/site.yml"
        label: "Textos e Contatos"
        name: "dados"
        fields:
          - {label: "Título Sobre", name: "sobre_titulo", widget: "string"}
          - {label: "Texto Sobre", name: "sobre_texto", widget: "text"}
          - {label: "WhatsApp (apenas números)", name: "whatsapp", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
